package model;

import model.base.BaseAuditorium;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Auditorium extends BaseAuditorium<Auditorium> {
	public static final Auditorium dao = new Auditorium().dao();
}
