package model;

import model.base.BaseBooking;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Booking extends BaseBooking<Booking> {
	public static final Booking dao = new Booking().dao();
}
