package model;

import model.base.BaseDobanComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DobanComment extends BaseDobanComment<DobanComment> {
	public static final DobanComment dao = new DobanComment().dao();
}
