package model;

import model.base.BaseDoubanComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DoubanComment extends BaseDoubanComment<DoubanComment> {
	public static final DoubanComment dao = new DoubanComment().dao();
}
