package model;

import model.base.BaseDoubanReviewTop250;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DoubanReviewTop250 extends BaseDoubanReviewTop250<DoubanReviewTop250> {
	public static final DoubanReviewTop250 dao = new DoubanReviewTop250().dao();
}
