package model;

import model.base.BaseMovieTop250;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MovieTop250 extends BaseMovieTop250<MovieTop250> {
	public static final MovieTop250 dao = new MovieTop250().dao();
}
