package model;

import model.base.BaseMovie;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Movie extends BaseMovie<Movie> {
	public static final Movie dao = new Movie().dao();
}
