package model;

import model.base.BaseRecommendation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recommendation extends BaseRecommendation<Recommendation> {
	public static final Recommendation dao = new Recommendation().dao();
}
