package model;

import model.base.BaseSeat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Seat extends BaseSeat<Seat> {
	public static final Seat dao = new Seat().dao();
}
