package model;

import model.base.BaseShowing;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Showing extends BaseShowing<Showing> {
	public static final Showing dao = new Showing().dao();
}
