package model;

import model.base.BaseTheater;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Theater extends BaseTheater<Theater> {
	public static final Theater dao = new Theater().dao();
}
