package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTheater<M extends BaseTheater<M>> extends Model<M> implements IBean {

	public void setTheaterId(java.lang.Integer theaterId) {
		set("theater_id", theaterId);
	}

	public java.lang.Integer getTheaterId() {
		return get("theater_id");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setTheater(java.lang.String theater) {
		set("theater", theater);
	}

	public java.lang.String getTheater() {
		return get("theater");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setRegisterTime(java.util.Date registerTime) {
		set("register_time", registerTime);
	}

	public java.util.Date getRegisterTime() {
		return get("register_time");
	}

}
