package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBooking<M extends BaseBooking<M>> extends Model<M> implements IBean {

	public void setBookingId(java.lang.Integer bookingId) {
		set("booking_id", bookingId);
	}

	public java.lang.Integer getBookingId() {
		return get("booking_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setShowingId(java.lang.Integer showingId) {
		set("showing_id", showingId);
	}

	public java.lang.Integer getShowingId() {
		return get("showing_id");
	}

	public void setSeatId(java.lang.Integer seatId) {
		set("seat_id", seatId);
	}

	public java.lang.Integer getSeatId() {
		return get("seat_id");
	}

	public void setPurchaseTime(java.util.Date purchaseTime) {
		set("purchase_time", purchaseTime);
	}

	public java.util.Date getPurchaseTime() {
		return get("purchase_time");
	}

	public void setPurchasePrice(java.math.BigDecimal purchasePrice) {
		set("purchase_price", purchasePrice);
	}

	public java.math.BigDecimal getPurchasePrice() {
		return get("purchase_price");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

}
