package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDoubanComment<M extends BaseDoubanComment<M>> extends Model<M> implements IBean {

	public void setCommentId(java.lang.String commentId) {
		set("comment_id", commentId);
	}

	public java.lang.String getCommentId() {
		return get("comment_id");
	}

	public void setMovieId(java.lang.Integer movieId) {
		set("movie_id", movieId);
	}

	public java.lang.Integer getMovieId() {
		return get("movie_id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUsefulCount(java.lang.Integer usefulCount) {
		set("useful_count", usefulCount);
	}

	public java.lang.Integer getUsefulCount() {
		return get("useful_count");
	}

	public void setRating(java.lang.Integer rating) {
		set("rating", rating);
	}

	public java.lang.Integer getRating() {
		return get("rating");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}

	public java.lang.String getAvatar() {
		return get("avatar");
	}

	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}

	public java.lang.String getTags() {
		return get("tags");
	}

}
