package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShowing<M extends BaseShowing<M>> extends Model<M> implements IBean {

	public void setShowingId(java.lang.Integer showingId) {
		set("showing_id", showingId);
	}

	public java.lang.Integer getShowingId() {
		return get("showing_id");
	}

	public void setMovieId(java.lang.Integer movieId) {
		set("movie_id", movieId);
	}

	public java.lang.Integer getMovieId() {
		return get("movie_id");
	}

	public void setShowTime(java.util.Date showTime) {
		set("show_time", showTime);
	}

	public java.util.Date getShowTime() {
		return get("show_time");
	}

	public void setAuditoriumId(java.lang.Integer auditoriumId) {
		set("auditorium_id", auditoriumId);
	}

	public java.lang.Integer getAuditoriumId() {
		return get("auditorium_id");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

}
