package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDoubanReviewTop250<M extends BaseDoubanReviewTop250<M>> extends Model<M> implements IBean {

	public void setReviewId(java.lang.Integer reviewId) {
		set("review_id", reviewId);
	}

	public java.lang.Integer getReviewId() {
		return get("review_id");
	}

	public void setMovieId(java.lang.Integer movieId) {
		set("movie_id", movieId);
	}

	public java.lang.Integer getMovieId() {
		return get("movie_id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

}
