package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCollection<M extends BaseCollection<M>> extends Model<M> implements IBean {

	public void setCollectionId(java.lang.Integer collectionId) {
		set("collection_id", collectionId);
	}

	public java.lang.Integer getCollectionId() {
		return get("collection_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setMovieId(java.lang.Integer movieId) {
		set("movie_id", movieId);
	}

	public java.lang.Integer getMovieId() {
		return get("movie_id");
	}

}
