package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuditorium<M extends BaseAuditorium<M>> extends Model<M> implements IBean {

	public void setAuditoriumId(java.lang.Integer auditoriumId) {
		set("auditorium_id", auditoriumId);
	}

	public java.lang.Integer getAuditoriumId() {
		return get("auditorium_id");
	}

	public void setAuditorium(java.lang.String auditorium) {
		set("auditorium", auditorium);
	}

	public java.lang.String getAuditorium() {
		return get("auditorium");
	}

	public void setTheaterId(java.lang.Integer theaterId) {
		set("theater_id", theaterId);
	}

	public java.lang.Integer getTheaterId() {
		return get("theater_id");
	}

}
