package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecommendation<M extends BaseRecommendation<M>> extends Model<M> implements IBean {

	public void setRecommendationId(java.lang.Integer recommendationId) {
		set("recommendation_id", recommendationId);
	}

	public java.lang.Integer getRecommendationId() {
		return get("recommendation_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setTop250Id(java.lang.Integer top250Id) {
		set("top250_id", top250Id);
	}

	public java.lang.Integer getTop250Id() {
		return get("top250_id");
	}

}
